config/routes.rb
Rails.application.routes.draw do


	#creates a location (url)
	#':story_id' is defined in 'comments_controller.rb' with '@comment.story_id = params[:story_id]'' (segments prefixed with ':' are variable)
	#send that to the ????? with to: 'xxx'
	# get  "/stories/:story_id/comments/new", to: "comments#new"

  resources :stories do
    #specify the only standard conventions we want
    #nested resource - puts '/stories' before in url
    resources :comments, only: [:new, :create, :edit, :update]
    resources :votes, only: [:create, :delete]
  end

  root "stories#index"
end


=begin
 resources keyword gives us standard conventions
  - 
  -
  -
  root defines home
=end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :story
	validates :body, length: {minimum: 10, maximum: 2000}

end

app/models/story.rb
class Story < ActiveRecord::Base

#can be length, unique, etc. this is wheere you 'model' your objects

# http://guides.rubyonrails.org/active_record_basics.html#validations
# http://api.rubyonrails.org/ search "validates"

	validates :title, presence: true
	validates :body, presence: true
	validates :url, presence: true, uniqueness: true

	has_many :comments
	has_many :votes

end

app/models/vote.rb
class Vote < ActiveRecord::Base

	# Add counter cache for liking things
	belongs_to :story, counter_cache: true

	#people can only vote once
	validates :ip_address, uniqueness: { scope: :story_id }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new

  	# This is for the form
  	@story = Story.find(params[:story_id]) # This comes from the URL

  	# Also for building the form
  	@comment = Comment.new
  	
  	# We no longer need ro explicity set the story_id
  	# The form is being built from @story
  	# This outs the story id in the input field. We dont want that so the user cant edit
  	# @comment.story_id = params[:story_id]

  end

	def create
		@story = Story.find(params[:story_id])
		@comment = @story.comments.new(comment_params)

		if @comment.save
			flash[:success] = "That worked"
			redirect_to story_path(@story)
		else
			flash.now[:error] = "That didnt work"
			render :new
		end
	end

  def edit
  	@comment = Comment.find[:id]
  end

  private
	def comment_params
		# Only the data I whitelist is allowed through
		params.require(:comment).permit(:body, :story_id)
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	

#Shows all posts

	def index
		if params[:sort] == "recent"	
			#http://guides.rubyonrails.org/active_record_querying.html#ordering - ordering the results
			@stories = Story.order(created_at: :desc)
		elsif params[:filter] == "popular"
			@stories = Story.order(votes_count: :desc)
		elsif params[:filter] == "featured"
			@stories = Story.where(is_featured: true)
		else
			@stories = Story.order(created_at: :asc)
		end
	end



#Shows single post

	def show
		@story = Story.find(params[:id])
		@comments = @story.comments
	end



#allows to create new

	def new
		@story = Story.new
	end



# recieves data for new post

	def create
		@story = Story.new(story_params)
		if @story.save
			flash[:success] = "That worked"
			redirect_to root_path
		else
			flash[:error] = "That didnt work"
			render :new
		end
	end



# allows to edit post

	def edit
		@story = Story.find(params[:id])
	end	



# recieves data for edited post

	def update
		@story = Story.find(params[:id])

		if @story.update(story_params)
			flash[:success] = "That worked"
			redirect_to story_path(@story)
		else
			flash[:error] = "That didnt work"
			render :new
		end

	end



# allows to delete post

	def destroy
		@story = Story.find(params[:id])
		@story.delete
		flash[:success] = "Deleted"
		redirect_to root_path
	end



#to only accept allowed data from story_params in create and update. need to add each item here.

	private
	def story_params
		# Only the data I whitelist is allowed through
		params.require(:story).permit(:title, :body, :url, :is_featured)
	end
	
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		@vote = Vote.new(story_id: params[:story_id])
		@vote.ip_address = request.ip

		if @vote.save
			flash[:success] = "That worked"
			redirect_to root_path(filter: "popular")
		else
			flash[:error] = "You can't vote again"
			redirect_to root_path(filter: "popular")
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<%# param[:story_id] %>

<!-- uses an array as its nested -->
<%= simple_form_for [@story, @comment] do |f| %>

	<%= f.input :body %>
	<%# f.input :story_id %> 
	
	<%= f.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<div class="wrapper">
			<nav>
				<%= link_to "Stack", stories_path %>
				<%= link_to "Submit", new_story_path %>

				<!-- GOing back to same page, but updated -->
				<%= link_to "Recent", root_path(sort: "recent") %>
				<%= link_to "Top", root_path(filter: "popular") %>
				<%= link_to "Featured", root_path(filter: "featured") %>
			</nav>
		</div>
	</header>

	<div class="wrapper">

		<% flash.each do |the_flash_key, the_flash_value| %>

			<div class="<%= the_flash_key %>">
				<p><%= the_flash_value %></p>
			</div>
			
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/stories/_form.html.erb
<!-- 'form_for' is the standard form. 'simple_form_for' is for the simple form gem -->


<%= simple_form_for @story do |form| %>

	<!-- usuall would use 'form.text_field' change for simple form -->
	<!-- would also use '%= form.label :title %>' to generate form labels without simple form -->

	<%= form.input :title, placeholder: "Title" %>
	<!-- class adds css class, can be any attribute, eg 'alt'. html tags, eg <div> can also be placed around -->
	<%= form.input :body, class: "body" %>
	<%= form.input :url %>

	<%= form.input :is_featured %>

	<%= form.submit %>
<% end %>

app/views/stories/edit.html.erb
<!-- Includes the '/stories/_form.html.erb' file (these are in the same '/stories' directory) -->

<%= render "form" %>

app/views/stories/index.html.erb
<!-- here we turn "@stories" (from the controller) into "story" with a block (a loop) -->


<% @stories.each do |story| %>

<!-- here we reference "story" from above -->
	<div class="story">
		<h1><%= link_to story[:title], story_path(story) %></h1>
		<div class="upvote">
			<span><%= story.votes.count %></span>
			<%= link_to "Upvote", story_votes_path(story), method: :post %>
			<%= link_to "Downvote", story_votes_path(story), method: :delete %>
		</div>

		<p><%= story[:body] %></p>
		<%= link_to "Comments", story_path(story) %>
	</div>

<% end %>

app/views/stories/new.html.erb
<!-- Includes the '/stories/_form.html.erb' file (these are in the same '/stories' directory) -->

<%= render "form" %>

app/views/stories/show.html.erb
<!-- Here we reference "@story" from the controller -->

<h1><%= link_to @story.title, @story.url, target: "_blank" %></h1>
<em><%= @story.url %></em>
<p><%= @story.body %></p>


<div class="story-options">
	<!-- Add in dynamic story id with '@story' at end -->
	<%= link_to "Add a comment", new_story_comment_path(@story) %>
	<%= link_to "Feature this story", new_story_comment_path(@story) %>

	<!-- 'edit_story_path' comes from helper in left hand col of rake routes + '_path' -->
	<%= link_to "Edit", edit_story_path %>
	<%= link_to "Delete", story_path(@story), method: :delete %>
</div>


<div class="comments">
	<h2>Comments</h2>

	<% if @comments.any? %>

		<% @comments.each do |comment| %>
			<div class="comment">

				<!-- simple_format looks at the formating of the comment - adding carriage returns -->
				<%= simple_format comment.body %>
				<div class="time">
					<%= time_ago_in_words comment.created_at %>
				</div>
			</div>
		<% end %>

	<% else %>

		<p>No comments yet. You should <%= link_to "post one", new_story_comment_path(@story) %>.</p>

	<% end %>


</div>